name: Forge Tests
on:
  push:
    branches:
      - master
  pull_request:

# TODO : set up matrx for Arbitrum / BSC
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Pull library deps
        run: forge update

      - name: Run forge tests
        run:
          forge test -vvvvv -f $INFURA_ARBITRUM_RINKEBY
        env:
          INFURA_ARBITRUM_RINKEBY: ${{ secrets.INFURA_ARBITRUM_RINKEBY }}