networks:
    default: hardhat-arbitrum-fork

compiler:
  solc:
    version: 0.8.4
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0'
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0